Debug: true
Autosave interval: 10
Cooldowns:
  Enabled: true
  Decrement frequency: 5
Players:
  Files:
    Inactive check: 600
    Inactive time: 300
Selections:
  Use WorldEdit: false
  Global wand: RECORD_9:0
Signs:
  Enabled: true
  Interact delay: 20
  Enable InSigns: true
  Formats:
    Provider not found:
    - '&a&l\u300AGamegine\u300B'
    - '&4&oNOT FOUND'
    - ''
    - '&c{PROVIDER}'