name: ${project.name}
version: ${project.version}
description: 'Game library for Bukkit'
depend: []
softdepend: [InSigns, WorldEdit, WorldGuard]
author: Stealth2800
website: http://stealthyone.com
main: com.stealthyone.mcb.gamegine.GameginePlugin
commands:
  cooldown:
    aliases: [ggc, cooldowns]
  gamegine:
    aliases: [gg]
  games:
    aliases: []
  points:
    aliases: [ggpoints, gamepoints]
  gameginesign:
    aliases: [gsign, ggsign]