name: ${project.name}
version: ${project.version}
description: 'API for creating compatibility among different game plugins and tool for creating games easily and quickly'
depend: []
softdepend: [InSigns, WorldEdit]
author: Stealth2800
website: http://stealthyone.com
main: com.stealthyone.mcb.gamegine.GameginePlugin
commands:
  cooldown:
    aliases: [ggc, cooldowns]
  gamegine:
    aliases: [gg]
  games;
    aliases: []
  points:
    aliases: [ggpoints, gamepoints]