name: ${project.name}
version: ${project.version}
description: '${project.description}'
depend: []
softdepend: [InSigns, WorldEdit, WorldGuard]
authors: [${project.authors}]
website: ${project.url}
main: ${project.mainClass}
commands:
  gamegine:
    aliases: [gg]
  gameginegames:
    aliases: [games, game, ggames, ggame]
  gamegineselection:
    aliases: [ggsel, gsel, sel, selection]
  gameginesigns:
    aliases: [signs, sign, gsigns, gsign]
permissions:
  #####################
  # Permission groups #
  #####################
  gamegine.admin:
    description: 'Gives access to all admin commands.'
    default: op
    children:
      gamegine.admin.selections: true
      gamegine.admin.signs: true
      gamegine.reload: true
      gamegine.save: true
  gamegine.admin.selections:
    description: 'Gives access to all selection permissions.'
    default: false
    children:
      gamegine.selections.create: true
      gamegine.selections.info: true
      gamegine.selections.type: true
  gamegine.admin.signs:
    description: 'Gives access to all sign permissions.'
    default: false
    children:
      gamegine.signs.create: true
      gamegine.signs.info: true
      gamegine.signs.list: true
      gamegine.signs.teleport: true
      gamegine.signs.types: true
  gamegine.player.play:
    description: 'Gives access to the basic gameplay permissions.'
    default: true
    children:
      gamegine.games.join: true
      gamegine.games.leave: true
      gamegine.games.list: true

  ###################
  # Plugin commands #
  ###################
  gamegine.reload:
    description: 'Allows a player to reload Gamegine''s configuration.'
    default: false
  gamegine.save:
    description: 'Allows a player to save Gamegine''s data and configuration.'
    default: false

  #################
  # Game commands #
  #################
  gamegine.games.join:
    description: 'Allows a player to use Gamegine''s join command.'
    default: false
  gamegine.games.leave:
    description: 'Allows a player to use Gamegine''s leave command.'
    default: false
  gamegine.games.list:
    description: 'Allows a player to list all of the currently registered games.'
    default: false

  ######################
  # Selection commands #
  ######################
  gamegine.selections.create:
    description: 'Allows a player to create a selection.'
    default: false
  gamegine.selections.info:
    description: 'Allows a player to view their current selection information.'
    default: false
  gamegine.selections.type:
    description: 'Allows a player to set their currently active selection handler.'
    default: false

  #################
  # Sign commands #
  #################
  gamegine.signs.create:
    description: 'Allows a player to create a Gamegine sign.'
    default: false
  gamegine.signs.info:
    description: 'Allows a player to view a Gamegine sign''s info.'
    default: false
  gamegine.signs.list:
    description: 'Allows a player to list registered Gamegine signs for a game.'
    default: false
  gamegine.signs.teleport:
    description: 'Allows a player to teleport to a registered Gamegine sign.'
    default: false
  gamegine.signs.types:
    description: 'Allows a player to view registered sign types.'
    default: false