name: Gamegine
version: 1.0
description: Bukkit minigame API to enable compatibility running multiple game plugins on a single server
depend: [StBukkitLib]
softdepend: [InSigns]
author: Stealth2800
website: http://stealthyone.com/bukkit
main: com.stealthyone.mcb.gamegine.Gamegine
commands:
  gamegine:
    aliases: [gg, game]
  points:
    aliases: [ggpoints, gamepoints]